# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xiaoai',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/xiaoai',
                'lib_path': 'xiaoai'},
  'syms': { 'xiaoai.core': { 'xiaoai.core.collate_dict': ('core.html#collate_dict', 'xiaoai/core.py'),
                             'xiaoai.core.inplace': ('core.html#inplace', 'xiaoai/core.py')}}}
