# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xiaoai',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/xiaoai',
                'lib_path': 'xiaoai'},
  'syms': { 'xiaoai.core': { 'xiaoai.core.collate_dict': ('core.html#collate_dict', 'xiaoai/core.py'),
                             'xiaoai.core.get_grid': ('core.html#get_grid', 'xiaoai/core.py'),
                             'xiaoai.core.inplace': ('core.html#inplace', 'xiaoai/core.py'),
                             'xiaoai.core.show_image': ('core.html#show_image', 'xiaoai/core.py'),
                             'xiaoai.core.show_images': ('core.html#show_images', 'xiaoai/core.py'),
                             'xiaoai.core.subplots': ('core.html#subplots', 'xiaoai/core.py')}}}
