"""Here, I attempt to train an autoencoder."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_autoencoder.ipynb.

# %% auto 0
__all__ = ['eval']

# %% ../nbs/08_autoencoder.ipynb 63
import torch
def eval(model, loss_func, valid_dl, epoch=0):
  model.eval()
  with torch.no_grad():
    loss, count = 0.,0
    for xb,_ in valid_dl:
      n = len(xb)
      count += n
      loss += loss_func(model(xb),xb).item()*n
  print(epoch, f'{loss/count:.3f}')

