"""In this notebook, I explore convolutions, and implement my own functions related to convolutions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_convolutions.ipynb.

# %% auto 0
__all__ = ['def_device', 'suplog', 'im2col', 'conv', 'to_device', 'collate_device']

# %% ../nbs/07_convolutions.ipynb 4
from contextlib import contextmanager
from traceback import print_exc

@contextmanager
def suplog():
  try: yield
  except Exception: print_exc()

# %% ../nbs/07_convolutions.ipynb 40
import torch

# %% ../nbs/07_convolutions.ipynb 214
def im2col(im:torch.Tensor, kw:int, kh:int, pad:bool|int=0, stride=1, dilation=1):
  im_ = im
  if pad:
    if kw==kh and isinstance(pad,bool): pad=kw//2
    im_ = torch.zeros(im.shape[0]+pad*2, im.shape[1]+pad*2)
    im_[pad:-pad,pad:-pad] = im

  matrix = []
  for r in range(0,im_.shape[0]-kw+1,stride):
    for c in range(0,im_.shape[0]-kh+1,stride):
      im__ = tensor(im_[r:r+kw,c:c+kh])
      im__[1:dilation],im__[:,1:dilation] = 0,0
      matrix.append(im__.flatten())
  return torch.stack(matrix)

# %% ../nbs/07_convolutions.ipynb 257
from torch import nn

# %% ../nbs/07_convolutions.ipynb 264
def conv(ni, nf, ks=3, stride=2, act=True):
  res = nn.Conv2d(ni, nf, kernel_size=ks, stride=stride, padding=ks//2)
  if act: res = nn.Sequential(res, nn.ReLU())
  return res

# %% ../nbs/07_convolutions.ipynb 274
from typing import Mapping
from torch.utils.data import default_collate

def_device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'
def to_device(x, device=def_device):
  if isinstance(x, torch.Tensor): return x.to(device)
  if isinstance(x, Mapping): return {k:v.to(device) for k,v in x.items()}
  return type(x)(to_device(o, device) for o in x)

def collate_device(b): return to_device(default_collate(b))
